logging:
  file:
    name: config-server.logs
    path: logs/
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/askPavan/global-configurations.git
          refresh-rate: 120
  security:
    user:
      name: admin 
      password: welcome